/*
 Navicat Premium Dump SQL

 Source Server         : 47.94.251.17
 Source Server Type    : MySQL
 Source Server Version : 80027 (8.0.27)
 Source Host           : 47.94.251.17:23306
 Source Schema         : plant-management

 Target Server Type    : MySQL
 Target Server Version : 80027 (8.0.27)
 File Encoding         : 65001

 Date: 23/03/2025 17:48:23
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for system_users
-- ----------------------------
DROP TABLE IF EXISTS `system_users`;
CREATE TABLE `system_users` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  `username` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户账号',
  `password` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '密码',
  `nickname` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户昵称',
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `dept_id` bigint DEFAULT NULL COMMENT '部门ID',
  `post_ids` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '岗位编号数组',
  `email` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '用户邮箱',
  `mobile` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '手机号码',
  `sex` tinyint DEFAULT '0' COMMENT '用户性别',
  `avatar` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '头像地址',
  `status` tinyint NOT NULL DEFAULT '0' COMMENT '帐号状态（0正常 1停用）',
  `login_ip` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '最后登录IP',
  `login_date` datetime DEFAULT NULL COMMENT '最后登录时间',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  `plant_tenant_id` bigint DEFAULT NULL COMMENT '种植租户编号',
  `enterprise_id` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '企业名称',
  `user_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '用户类型',
  `contact` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '联系人',
  `contact_phone` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '联系人电话',
  `service_type` int DEFAULT NULL COMMENT '服务类型',
  `audit_status` int DEFAULT NULL COMMENT '审核状态',
  `audit_reason` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '审核原因',
  `audit_time` datetime DEFAULT NULL COMMENT '审核时间',
  `register_ip` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '注册ip',
  `terminal` int DEFAULT NULL COMMENT '注册终端',
  `credit_code` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '统一社会信用代码',
  `enterprise_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '企业名称',
  `province` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '省',
  `city` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '市',
  `area` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '区',
  `address` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '详细地址',
  `register_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '注册类型',
  `openid` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '小程序id',
  `is_bind_wx` tinyint DEFAULT '0' COMMENT '是否绑定小程序',
  `mini_app_id` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '小程序appid',
  `province_id` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '所属省编码',
  `city_id` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '所属市编码',
  `area_id` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '所属区编码',
  `birthday` date DEFAULT NULL COMMENT '生日',
  `point` int DEFAULT '0' COMMENT '积分',
  `total_point` int DEFAULT '0' COMMENT '总积分',
  `tag_ids` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '会员标签列表，以逗号分隔',
  `level_id` bigint DEFAULT NULL COMMENT '会员级别编号',
  `experience` int DEFAULT '0' COMMENT '会员经验',
  `group_id` bigint DEFAULT NULL COMMENT '用户分组编号',
  `credit_id` bigint DEFAULT NULL COMMENT '所属合作社id',
  `tenant_type` bigint DEFAULT NULL COMMENT '租户类型',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_area` (`province_id`,`city_id`,`area_id`) COMMENT '地区索引'
) ENGINE=InnoDB AUTO_INCREMENT=251 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='用户信息表';

-- ----------------------------
-- Records of system_users
-- ----------------------------
BEGIN;
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (1, 'admin', '$2a$04$G6ryBWDjCn4q3C.8RWyJw.z0Vabw2pnxeMXeoC4faGf3FN.OPf3Ua', '农码通种植管理系统', '管理员', 100, '[1,2]', 'aoteman@126.com', '18818260277', 2, 'http://test.yudao.iocoder.cn/b61955916c8ace0ceb65080b7aeb71a3789acdac01661e0f264895a66fc324f5.png', 0, '221.232.106.137', '2025-03-22 17:32:48', 'admin', '2021-01-05 17:03:47', NULL, '2025-03-22 17:32:48', b'0', 1, 103, NULL, '1', NULL, NULL, NULL, 2, NULL, '2025-03-19 11:11:18', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, '420000', '420100', '420111', NULL, 0, 0, NULL, NULL, 0, NULL, NULL, 1);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (144, '18202770277', '$2a$04$bCMhgc65ZQQ90BWEDIGhCObOfKHIg2D20FZhCntBsK22HfvHFi8qK', '用户18202773184', NULL, NULL, NULL, '', '18202770277', 0, '', 0, '221.232.105.225', '2025-03-04 15:18:33', NULL, '2025-01-17 15:18:10', '163', '2025-03-13 02:32:38', b'0', 0, 1007, NULL, '3', NULL, NULL, 0, 1, NULL, NULL, NULL, NULL, '4454545544', 'huawei', '湖北省', '武汉市', '洪山区', '光谷', NULL, NULL, 0, NULL, '420000', '420100', '420111', NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (206, 'zhuli', '$2a$04$oLHqY1/YxEc1WNKb5G4k4./5e8hs8kWfIgsIst84yO37NyiiWNOOi', 'zl', '', 111, '[2,4,5]', '', '', 1, '', 0, '59.172.35.148', '2025-03-13 11:56:04', '1', '2025-03-13 11:20:03', NULL, '2025-03-13 11:56:05', b'0', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (207, 'zzzz', '$2a$04$RvvyZtDVZy2xQV9up2Q8Ae/CpxYkfD8N6TcWDuYxApO1IYA7ZjYLC', 'zzz', '', NULL, '[]', '', '', 0, '', 1, '', NULL, '1', '2025-03-13 11:35:46', '1', '2025-03-13 14:06:43', b'1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (208, '18100000000', '$2a$04$YVAU3pnILxo.vhm2qcVNieCgK3M0wPEZCUzsew3l6.UWhWOzSiYXC', '游客', '', 100, '[]', '', '18100000000', 0, '', 0, '171.219.163.79', '2025-03-22 11:18:35', '1', '2025-03-13 14:03:58', '208', '2025-03-22 11:18:35', b'0', 0, NULL, NULL, NULL, NULL, NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, 2);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (212, 'zl123456', '$2a$04$RjhhkZ031lzCAqo.2K4.JevleWkAG0A1Lryf.xg.LvviFdzlmNKse', 'zz', NULL, NULL, NULL, '', '', 0, '', 1, '59.172.35.148', '2025-03-13 16:09:45', NULL, '2025-03-13 16:08:59', '1', '2025-03-13 16:23:47', b'0', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (213, '1111', '$2a$04$Gpsdz0v10cwqrexEJez7pedQFS8wtwZeCnE8ccn0j08dJUkC97ZgG', '111', NULL, NULL, NULL, '', '111', 0, '', 0, '', NULL, '1', '2025-03-13 17:40:30', '1', '2025-03-13 17:40:30', b'0', 0, 117, NULL, '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', '', '', NULL, NULL, NULL, 0, NULL, '', '', '', NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (214, '111', '$2a$04$VcqFJtlWI3rl5rbomvlcI.jYtftsFovIW.1tcLM.inbqzz/yi.fSW', '111', NULL, NULL, NULL, '', '11111111111111', 0, '', 0, '', NULL, '1', '2025-03-14 09:46:47', '1', '2025-03-14 09:46:47', b'0', 0, 119, NULL, '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '北京市', '北京市', '西城区', NULL, NULL, NULL, 0, NULL, '110000', '110100', '110102', NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (219, 'test', '$2a$04$H/2EQF2nTXQUKeLooMpWsOTjEwFzngTHsSmK9OctLp8.ak9dpHblS', '马云', NULL, NULL, NULL, '', '13785474125', 0, '', 0, '', NULL, '1', '2025-03-14 16:10:50', '1', '2025-03-14 16:10:50', b'0', 0, NULL, NULL, '6', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '北京市', '北京市', NULL, NULL, NULL, NULL, 0, NULL, '110100', '110000', NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (220, 'tests', '$2a$04$6UsbFuhh8CaVBwpPEc83mOIg4aoFVoHrqR8OvU.CUx/6tdGDQE.Y2', '马化腾', NULL, NULL, NULL, '', '123456789', 0, '', 0, '', NULL, '1', '2025-03-14 16:40:37', '1', '2025-03-14 16:40:37', b'0', 0, NULL, NULL, '6', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '深圳市', '广东省', NULL, NULL, NULL, NULL, 0, NULL, '440300', '440000', NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (221, '18202770513', '123456', '微信用户18202770513', NULL, NULL, NULL, '', '18202770513', 0, '', 0, '221.232.106.137', '2025-03-18 13:57:10', NULL, '2025-03-15 09:46:15', NULL, '2025-03-18 13:57:10', b'0', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '221.232.106.137', 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'oCV9Y7Bry7fmjkkTrCm2_HJtW0BQ', 1, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, 0);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (222, '18202773184', '123456', '微信用户18202773184', NULL, NULL, NULL, '', '18202773184', 0, '', 0, '117.152.93.190', '2025-03-18 20:22:33', '221', '2025-03-15 09:47:06', '221', '2025-03-18 20:22:33', b'0', 0, 120, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '221.232.106.137', 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'oCV9Y7Bry7fmjkkTrCm2_HJtW0BQ', 1, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, 0);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (223, '15926479511', '123456', '微信用户15926479511', NULL, NULL, NULL, '', '15926479511', 0, '', 0, '221.232.106.137', '2025-03-21 14:15:32', '208', '2025-03-15 11:27:41', '223', '2025-03-21 14:15:32', b'0', 0, 184, NULL, NULL, NULL, NULL, NULL, 1, NULL, '2025-03-21 09:55:42', '221.232.106.137', 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'oCV9Y7JRvCERxrZt51U1mH2_PSuU', 1, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, 1);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (224, '13510321669', '123456', '微信用户13510321669', NULL, NULL, NULL, '', '13510321669', 0, '', 0, '103.98.240.79', '2025-03-23 12:01:45', '208', '2025-03-15 19:37:50', '224', '2025-03-23 12:01:45', b'0', 0, 129, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '103.98.241.79', 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'oCV9Y7H9Sv1_OqABvBPCiLxXZdxg', 1, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, 5);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (225, '18827419801', '123456', '微信用户18827419801', NULL, NULL, NULL, '', '18827419801', 0, '', 0, '221.232.120.21', '2025-03-17 17:19:57', '142', '2025-03-17 11:03:15', '1', '2025-03-17 17:22:14', b'1', 0, 122, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '221.232.120.21', 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'oCV9Y7M0a39snImSAiRZtjbLUHQI', 1, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, 0);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (226, 'test0317', '$2a$04$gkCrCANg4LomXcA9TJDgmeuffJiGPgv..MgufIsVPUQEgEVJBCNWa', '111', NULL, NULL, NULL, '', '111', 0, '', 0, '', NULL, '1', '2025-03-17 15:26:57', '1', '2025-03-17 17:38:57', b'1', 0, 128, NULL, '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (227, '19947624916', '123456', '微信用户19947624916', NULL, NULL, NULL, '', '19947624916', 0, '', 0, '59.174.60.36', '2025-03-19 10:08:22', '225', '2025-03-17 17:16:38', '237', '2025-03-19 10:08:22', b'0', 0, 130, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '221.232.120.21', 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'oCV9Y7M0a39snImSAiRZtjbLUHQI', 1, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, 0);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (228, '15172441694', '123456', '微信用户15172441694', NULL, NULL, NULL, '', '15172441694', 2, '', 0, '221.232.106.137', '2025-03-19 10:43:18', NULL, '2025-03-18 10:25:11', NULL, '2025-03-19 02:48:08', b'1', 0, 133, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, '221.232.106.137', 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'oCV9Y7JeFeM8PliYW8kJkYsRtQeg', 1, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, 0);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (229, '13260561082', '123456', '微信用户13260561082', NULL, NULL, NULL, '', '13260561082', 0, '', 0, '221.232.106.137', '2025-03-18 15:25:28', NULL, '2025-03-18 15:25:28', NULL, '2025-03-18 15:25:28', b'0', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '221.232.106.137', 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'oCV9Y7JeFeM8PliYW8kJkYsRtQeg', 1, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, 0);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (230, '18637627061', '123456', '微信用户18637627061', NULL, NULL, NULL, '', '18637627061', 0, '', 0, '221.232.106.137', '2025-03-18 19:36:26', NULL, '2025-03-18 16:19:31', '230', '2025-03-18 19:36:26', b'0', 0, 138, NULL, NULL, NULL, NULL, NULL, 2, NULL, '2025-03-18 16:58:15', '221.232.106.137', 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'oCV9Y7Ogbqvlr8lqqdDxftfJXzG4', 1, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, 5);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (231, 'sp', '$2a$04$ya/SXRBuaS8GgeytvxoTguyeEDPWbOfnOYeqzL20/M9b/NJHRShk2', '123', NULL, NULL, NULL, '', '123', 0, '', 0, '', NULL, '1', '2025-03-18 16:40:18', '1', '2025-03-18 16:40:18', b'0', 0, 139, NULL, '4', NULL, NULL, NULL, 2, NULL, '2025-03-18 16:41:31', NULL, NULL, NULL, NULL, '北京市', '北京市', '东城区', NULL, NULL, NULL, 0, NULL, '110000', '110100', '110101', NULL, 0, 0, NULL, NULL, 0, NULL, NULL, 4);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (232, 'fw', '$2a$04$7gLVL0t9DOOtesxmFa.LTe9CW6XZfCoRlFj58dkFyyVX9UVhW7trG', '1111', NULL, NULL, NULL, '', '1111', 0, '', 0, '', NULL, '1', '2025-03-18 16:47:25', '1', '2025-03-18 16:47:25', b'0', 0, 140, NULL, '3', NULL, NULL, NULL, 2, NULL, '2025-03-18 16:47:44', NULL, NULL, NULL, NULL, '北京市', '北京市', '东城区', NULL, NULL, NULL, 0, NULL, '110000', '110100', '110101', NULL, 0, 0, NULL, NULL, 0, NULL, NULL, 3);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (233, 'sp01', '$2a$04$NTYplQM19i2cQGP7AtjKrOypPe2b58/5FI45O.ApLrAB6Vzr4e5lC', '111', NULL, NULL, NULL, '', '111', 0, '', 0, '', NULL, '1', '2025-03-18 16:58:18', '1', '2025-03-18 16:58:18', b'0', 0, 141, NULL, '4', NULL, NULL, NULL, 2, NULL, '2025-03-18 16:58:29', NULL, NULL, NULL, NULL, '北京市', '北京市', '东城区', NULL, NULL, NULL, 0, NULL, '110000', '110100', '110101', NULL, 0, 0, NULL, NULL, 0, NULL, NULL, 4);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (234, '17683858246', '$2a$04$b9FaFfgeFnLzTiFbSghiwuNDleGFEcKxQC17xm.wqPd6DL3mU4HW2', '王国威', NULL, NULL, NULL, '', '17683858246', 0, '', 0, '', NULL, '211', '2025-03-18 17:10:29', '211', '2025-03-18 17:10:29', b'0', 0, NULL, NULL, '2', NULL, NULL, NULL, 2, NULL, NULL, '221.232.106.137', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (235, '18827419801', '123456', '微信用户18827419801', NULL, NULL, NULL, '', '18827419801', 0, '', 0, '59.174.60.36', '2025-03-19 10:07:46', NULL, '2025-03-18 17:48:54', '1', '2025-03-19 10:08:01', b'1', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '171.82.96.10', 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'oCV9Y7M0a39snImSAiRZtjbLUHQI', 1, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, 0);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (236, '13476112390', '123456', '微信用户13476112390', NULL, NULL, NULL, '', '13476112390', 0, '', 0, '221.232.106.137', '2025-03-18 18:00:09', NULL, '2025-03-18 18:00:08', NULL, '2025-03-18 18:00:09', b'0', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '221.232.106.137', 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'oCV9Y7CJs6ztcbdVxaNIa8tYtvIQ', 1, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, 0);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (237, '18827419801', '123456', '微信用户18827419801', NULL, NULL, NULL, '', '18827419801', 0, '', 0, '171.210.219.199', '2025-03-21 14:17:44', '235', '2025-03-19 10:08:12', '237', '2025-03-21 14:17:44', b'0', 0, 180, NULL, NULL, NULL, NULL, NULL, 2, NULL, '2025-03-19 15:24:48', '59.174.60.36', 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'oCV9Y7M0a39snImSAiRZtjbLUHQI', 1, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, 1);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (238, '123456789', '$2a$04$WLUTuor1lvc2b7XnJpRj7uQSXwdtN69ttZBxGtyphQKdQ9yoKXsNK', '马化腾', NULL, NULL, NULL, '', '987654321', 0, '', 0, '', NULL, '1', '2025-03-19 10:24:15', '1', '2025-03-19 10:24:15', b'0', 0, NULL, NULL, '6', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '天津市', '天津市', NULL, NULL, NULL, NULL, 0, NULL, '120000', '120100', NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (239, 'test01', '$2a$04$/nG7/NwJ7rd7NniA4fjxfuKphM34MnCve4rbBiE.kD7UI/HPgPP3i', 'zz', NULL, NULL, NULL, '', '15171517151', 0, '', 0, '', NULL, '1', '2025-03-19 10:25:15', '1', '2025-03-19 10:25:15', b'0', 0, NULL, NULL, '6', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '河北省', '石家庄市', NULL, NULL, NULL, NULL, 0, NULL, '130000', '130100', NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (240, '15172441694', '123456', '微信用户15172441694', NULL, NULL, NULL, '', '15172441694', 0, '', 0, '221.232.106.137', '2025-03-22 18:03:36', NULL, '2025-03-19 10:48:42', '240', '2025-03-22 18:03:36', b'0', 0, 182, NULL, NULL, NULL, NULL, NULL, 2, NULL, '2025-03-20 10:34:28', '221.232.106.137', 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'oCV9Y7JeFeM8PliYW8kJkYsRtQeg', 1, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, 1);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (241, '15872975167', '123456', '微信用户15872975167', NULL, NULL, NULL, '', '15872975167', 2, '', 0, '221.232.106.137', '2025-03-22 18:18:55', '211', '2025-03-19 11:01:34', '241', '2025-03-22 18:18:55', b'0', 0, 170, NULL, NULL, NULL, NULL, NULL, 2, NULL, '2025-03-22 17:19:24', '221.232.106.137', 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'oCV9Y7FzIL3QI33YY6YjeSMWSRnQ', 1, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, 1);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (242, '18838941277', '123456', '微信用户18838941277', NULL, NULL, NULL, '', '18838941277', 0, '', 0, '221.232.106.137', '2025-03-20 14:02:35', '217', '2025-03-19 14:35:45', '217', '2025-03-20 14:02:35', b'0', 0, 179, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, '221.232.106.137', 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'oCV9Y7GpxPD9__BjecLmXs1p5E8I', 1, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, 0);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (243, '0319test', '$2a$04$QwdJNplL/LnIlWnYqF2PA.WDQoskulCMQbRMp3EnP4jgi/BNfC2Fi', 'zzzz', '她她她她她她她她她', NULL, NULL, '2684135866@qq.com', '15172441666', 0, '', 0, '221.232.106.137', '2025-03-19 17:46:50', '1', '2025-03-19 15:51:23', NULL, '2025-03-19 17:46:50', b'0', 0, 181, NULL, '3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '河北省', '唐山市', '路北区', NULL, NULL, NULL, 0, NULL, '130000', '130200', '130203', NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (244, '151724699', '$2a$04$sr//1uJtwq5kVr4yzFUzceSsATMmzEStHY9U0KS6NiBlZg4hrlKae', 'zl001', NULL, NULL, NULL, '', '151724699', 0, '', 0, '', NULL, '240', '2025-03-20 14:38:19', '240', '2025-03-20 14:38:19', b'0', 0, 170, NULL, NULL, NULL, NULL, NULL, 2, NULL, NULL, '221.232.106.137', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (245, '18132323232', '$2a$04$67x6tDqcaA0azX.f410b8OzhG0YU5K2sL4PRhfKwN0C4gW7izOm.a', '掌扇', NULL, NULL, NULL, '', '18132323232', 0, '', 0, '103.98.240.79', '2025-03-23 12:01:25', '1', '2025-03-20 14:39:23', '245', '2025-03-23 12:01:25', b'0', 0, 183, NULL, '3', NULL, NULL, NULL, 2, NULL, '2025-03-20 14:39:46', NULL, NULL, NULL, NULL, '北京市', '北京市', '东城区', NULL, NULL, NULL, 0, NULL, '110000', '110100', '110101', NULL, 0, 0, NULL, NULL, 0, NULL, NULL, 3);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (246, '15172441699', '$2a$04$FgGL13Iwel24BDrPbIS2o.sVCsEbbAGY3X4xd0iIb07PhRlpclzJi', 'zl001', NULL, NULL, NULL, '', '15172441699', 0, '', 0, '', NULL, '240', '2025-03-20 14:43:17', '240', '2025-03-20 14:43:17', b'0', 0, 179, NULL, NULL, NULL, NULL, NULL, 2, NULL, NULL, '221.232.106.137', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (247, '18964513875', '$2a$04$HnEiUYegtuKUV.Dbqfzmi..DJ9PvL1AIlWa/j6RgF.tTWPTi7fITq', '张三三', NULL, NULL, NULL, '', '18964513875', 0, '', 0, '', NULL, '245', '2025-03-20 15:23:58', '245', '2025-03-21 08:13:23', b'0', 0, NULL, NULL, '3', NULL, NULL, NULL, 0, NULL, NULL, '59.174.60.36', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (248, 'zhuli002', '$2a$04$ucMHBnHx3LZyO21QCmLmD.HhhtsFWCHj00X/mgbfKZ8MM8ccrlmE.', 'zl', NULL, NULL, '[]', '2684135861@qq.com', '15172441611', 2, '', 0, '', NULL, '1', '2025-03-21 14:35:27', '1', '2025-03-21 14:35:27', b'0', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (249, '13720280847', '123456', '微信用户13720280847', NULL, NULL, NULL, '', '13720280847', 0, '', 0, '223.104.122.56', '2025-03-21 15:37:21', '142', '2025-03-21 15:37:20', '142', '2025-03-21 15:37:21', b'0', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '223.104.122.56', 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'oCV9Y7L_crSqPn40WVT-5KNYbcS0', 1, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, 0);
INSERT INTO `system_users` (`id`, `username`, `password`, `nickname`, `remark`, `dept_id`, `post_ids`, `email`, `mobile`, `sex`, `avatar`, `status`, `login_ip`, `login_date`, `creator`, `create_time`, `updater`, `update_time`, `deleted`, `tenant_id`, `plant_tenant_id`, `enterprise_id`, `user_type`, `contact`, `contact_phone`, `service_type`, `audit_status`, `audit_reason`, `audit_time`, `register_ip`, `terminal`, `credit_code`, `enterprise_name`, `province`, `city`, `area`, `address`, `register_type`, `openid`, `is_bind_wx`, `mini_app_id`, `province_id`, `city_id`, `area_id`, `birthday`, `point`, `total_point`, `tag_ids`, `level_id`, `experience`, `group_id`, `credit_id`, `tenant_type`) VALUES (250, '1234567', '$2a$04$IKmYUeTrBz.S0/6lSXqkweHTNzhYQy6eflbb31wVIhq8K7IAj9svC', '王国威', NULL, NULL, NULL, '', '1234567', 0, '', 0, '', NULL, '241', '2025-03-22 17:23:11', '241', '2025-03-22 17:23:11', b'0', 0, 119, NULL, NULL, NULL, NULL, NULL, 2, NULL, NULL, '221.232.106.137', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL);
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
